# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrey Levkin
email: alevkin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  What i can say about me and my work? Why talk? Just doing. Just write there.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://andrey.levk.in" # the base hostname & protocol for your site
twitter_username: alevkin
github_username:  alevkin

# Build settings
markdown: kramdown
highlighter: rouge
